version: '3'

services:
  app: 
    build: 
      context: ./node
    container_name: node
    entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    volumes:
      - ./node:/home/node/app
    depends_on:
      - database
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80

  database:
    image: mysql
    container_name: database
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  node-network:
    driver: bridge